### ISSUE TITLE
Can't run trainer.py

### ISSUE THREAD

**Issue by khanhhoaa19** [moboehland/thyroidclassification#1]
I can't run file trainner.py, because file seg_module can't call "from models.unet import UNet".

**Comment by moboehland** [comment]
Thank you for your Issue. The repo was updated and you should be able to train a segmentation model on your data. Please see the new README.md file for the segmentation. Since I used the update to update some packages, you may need to create a new VE with the new requirements.yml file. If you continue to have problems running the scripts, feel free to reopen the issue.
